### PR TITLE
Update text (symbol) color

### PR DESCRIPTION
**Pull request by Greg-Smulko**
Update text (symbol) color - to match color in the current version of SSMS.

See changes in the `docs/demo-screenshot.png`.

### CODE REVIEW

**Comment by joshgoebel** [comment]
Why wouldn't you classify as string? Just curious.

**Comment by Greg-Smulko** [comment]
> Why wouldn't you classify as string? Just curious.

Sorry, just to clarify, I assume you're asking something along these lines:

> Why even bother with `hljs-symbol`, if you could just do nothing and have default black text?

If that's the question, then most likely you're right that at this point we don't need to bother with it, nor with the corresponding https://github.com/highlightjs/highlightjs-tsql/blob/bffc9a3eb6cf994a33b16d03f4ca4b22394e0dec/src/languages/tsql.js#L2661 .

What would be the gain here? A slight performance benefits, and that's the right thing to do in general?

And thanks for asking!

**Comment by joshgoebel** [comment]
No I mean it looks like a string, so why wouldn't you just scope it as a string vs changing the symbol color to match string?

**Comment by Greg-Smulko** [comment]
I think you're right. I suppose at this point we can remove the whole definition of the symbol https://github.com/highlightjs/highlightjs-tsql/blob/bffc9a3eb6cf994a33b16d03f4ca4b22394e0dec/src/languages/tsql.js#L2661 , as we just don't need it anymore - we don't want any specific colouring of symbols anymore after the default SSMS colour schema was changed.

**Pull request merged**
